version: '3.7'
services:
  back-end:
    image: huyphangia/9gag:back-end
    restart: on-failure
    depends_on:
      - database
    ports:
      - "80:8080"
  database:
    image: huyphangia/9gag:database
    volumes:
      - mssql-volume:/var/opt/mssql
volumes:
  mssql-volume: